#!/bin/sh

############################################################################
# MySQL Backup Script
#
# To install, set the BU_DIR directory.
# Create the ~/.my.cnf file with the password.
# Ex:
#   [client]
#   password=secret
# To run, add to /etc/cron.daily or run manually
#
# author: Joseph Lamoree <joseph@lamoree.com>
############################################################################

BU_USER=root
BU_DIR="/root/backups/mysql/`date +%Y.%m.%d`"
BU_BIN=/usr/bin/mysqldump
BU_OVERWRITE=0

umask 077

# Verify backup location
if [ ! -d `dirname $BU_DIR` ]; then
  echo "$0: Backup directory '`dirname $BU_DIR`' does not exist."
  exit 1
fi
if [ -d $BU_DIR ]; then
  if [ $BU_OVERWRITE -eq 0 ]; then
    echo "$0: Backup directory '$BU_DIR' already exists, and BU_OVERWRITE is off."
    exit 1
  else
    rm -rf $BU_DIR
  fi
fi

# Create the backup directory
mkdir $BU_DIR

# Dump all databases
su -l $BU_USER -s /bin/sh -c "$BU_BIN --all-databases --flush-logs --lock-tables --complete-insert" \
  | gzip > "$BU_DIR/mysqldump.`date +%Y.%m.%d`.gz"

